- public/Package_Management/Package_Management.py
- public/Package_Management/README.MD
- public/Package_Management/meta.json
> add Package_Management

- public/Bbox_Selection_Example/Bbox_Selection_Example.py
- public/Bbox_Selection_Example/meta.json
> fix the selection issue

- public/Time_Series_Example/Time_Series_Example.py
- public/Time_Series_Example/meta.json
fused_app -> fused for Times Series Example
> fused_app -> fused for Times Series Example

- public/Bbox_Selection_Example/Bbox_Selection_Example.py
this should fix the UDF call in the app
> update Bbox_Selection_Example to pass bounds instead of bbox

- public/Package_Management/Package_Management.py
- public/Package_Management/meta.json
> add whl support

- public/CDL_hex_demo/CDL_hex_demo.py
- public/CDL_hex_demo/README.MD
- public/CDL_hex_demo/meta.json
> CDL hex demo for CNG 

- public/CDL_hex_demo/CDL_hex_demo.py
- public/CDL_hex_demo/meta.json
> Update to pass year properly 

- public/CDL_hex_demo/CDL_hex_demo.py
> Adding all years we ingested

- public/CDL_hex5_visualize/CDL_hex5_visualize.py
- public/CDL_hex5_visualize/README.MD
- public/CDL_hex5_visualize/meta.json
> Creating CDL_hex5_visualize

- public/CDL_hex5_visualize/CDL_hex5_visualize.py
- public/CDL_hex5_visualize/meta.json
Using public UDF name, cleaning up tooltip
> Using public UDF name, cleaning up tooltip

- public/CDL_hex5_visualize/CDL_hex5_visualize.py
Adding description + link to Source Coop dataset
> Adding description + link to Source Coop dataset

- public/CDL_hex5_visualize/README.MD
Manually doing this, didn't find a good way to do this in Wb
> Updating cdl_hex5 thumbnail

- public/CDL_hex5_visualize/CDL_hex5_visualize.py
- public/CDL_hex5_visualize/README.MD
Updating UDF link to use public UDF naming scheme
> Updating UDF link to use public UDF naming scheme

- public/Explore_CDL_app/README.MD
- public/Explore_CDL_app/meta.json
Update thumbnail + description
> Update thumbnail + description

- public/Your_Name_in_Landsat/Your_Name_in_Landsat.py
- public/Your_Name_in_Landsat/meta.json
Updating api call to more up to date 
> Updating api call to more up to date 

- public/NDVI_Slider_Example/NDVI_Slider_Example.py
- public/NDVI_Slider_Example/README.MD
- public/NDVI_Slider_Example/meta.json
Adding context: title, description, links
> Adding context: title, description, links

- public/Emoji_Cheat_Sheet/Emoji_Cheat_Sheet.py
- public/Emoji_Cheat_Sheet/meta.json
update Emoji_Cheat_Sheet for new streamlit version
> update Emoji_Cheat_Sheet for new streamlit version

- public/Fused_Ingest_Form/Fused_Ingest_Form.py
- public/Fused_Ingest_Form/meta.json
> tweaks to ingest form app

- public/Contour_Slider_Example/Contour_Slider_Example.py
- public/Contour_Slider_Example/meta.json
fix Contour Slider Example for logged out users
> fix Contour Slider Example for logged out users

- public/S3_IAMpolicy_Form/S3_IAMpolicy_Form.py
- public/S3_IAMpolicy_Form/meta.json
Update to better support logged out user
> Update to better support logged out user

- public/Explore_CDL_app/Explore_CDL_app.py
- public/Explore_CDL_app/README.MD
Display percentage in histogram + smaller image preview 
> Display percentage in histogram + smaller image preview 

- public/Choropleth_Map_Example/Choropleth_Map_Example.py
- public/Choropleth_Map_Example/meta.json
Choropleth map example: Adding description + data link 
> Choropleth map example: Adding description + data link 

- public/Folium_Slider_Example/Folium_Slider_Example.py
- public/Folium_Slider_Example/meta.json
Adding title, description & link to data
> Adding title, description & link to data

- public/Explore_CDL_app/Explore_CDL_app.py
- public/Explore_CDL_app/README.MD
- public/Explore_CDL_app/meta.json
Explore CDL app adding 🌽 to title!
> Explore CDL app adding 🌽 to title!

- public/Webcam_Processing_Example/README.MD
- public/Webcam_Processing_Example/Webcam_Processing_Example.py
- public/Webcam_Processing_Example/meta.json
> add Webcam_Processing_Example

- public/Webcam_Processing_Example/Webcam_Processing_Example.py
Update webcam - using latest streamlit api
> Update webcam - using latest streamlit api

- public/Count_Airplanes/Count_Airplanes.py
fix Count Airplanes app, reformat
> fix Count Airplanes app, reformat
